In [ ]:
x = open("/content/drive/MyDrive/miRNA/mature.fa")
line = x.readline()
print(line)
line = x.readline()
print(line)

>cel-let-7-5p MIMAT0000001 Caenorhabditis elegans let-7-5p

UGAGGUAGUAGGUUGUAUAGUU

In [ ]:
a = "cel-let-7-5p MIMAT0000001 Caenorhabditis elegans let-7-5p"
b = "elegans"
if b in a: print(a)

cel-let-7-5p MIMAT0000001 Caenorhabditis elegans let-7-5p

In [ ]:
print()

cel-let-7-5p MIMAT0000001 Caenorhabditis elegans let-7-5p

# Mature seq

In [ ]:
mature = open("/content/drive/MyDrive/miRNA/mature.fa")

for i in range(10):
  line = mature.readline()
  print(line)

In [ ]:
mature = open("/content/drive/MyDrive/miRNA/mature.fa")
i = 1
mature_name = []
mature_seq = []
MIMAT = []
while line!="":
  i += 1
  line = mature.readline()
  if line=="": break
  if i%2 == 0:
    print(line)
    line = line.rstrip()
    line = line.split(" ")
    MIMAT.append(line[1])
    mature_name.append(line[0][1:])
  else:
    mature_seq.append(line.rstrip())

In [ ]:
# >cel-let-7-3p MIMAT0015091 Caenorhabditis elegans let-7-3p
print(mature_name[1], MIMAT[1], mature_seq[1])

cel-let-7-3p MIMAT0015091 CUAUGCAAUUUUCUACCUUACC

In [ ]:

d = {'MatureName': mature_name, "MIMAT": MIMAT, 'mature_seq': mature_seq}
df_mir_seq_convert = pd.DataFrame(data=d)
df_mir_seq_convert

               MatureName         MIMAT              mature_seq
0            cel-let-7-5p  MIMAT0000001  UGAGGUAGUAGGUUGUAUAGUU
1            cel-let-7-3p  MIMAT0015091  CUAUGCAAUUUUCUACCUUACC
2            cel-lin-4-5p  MIMAT0000002   UCCCUGAGACCUCAAGUGUGA
3            cel-lin-4-3p  MIMAT0015092  ACACCUGGGCUCUCCGGGUACC
4            cel-miR-1-5p  MIMAT0020301  CAUACUUCCUUACAUGCCCAUA
...                   ...           ...                     ...
48880    smc-miR-12461-3p  MIMAT0050488  AGUAAAUGAUCAGCAUCCUCCA
48881    gga-miR-1784b-5p  MIMAT0050489  UUCUGCUCCUAUUUAAGUCAAU
48882    gga-miR-1784b-3p  MIMAT0050490  UGAUUUCAAUAAGAGCAGAAUU
48883    mdo-miR-7385g-3p  MIMAT0050491   AGCAUAGAAUGUCAGAUCUAG
48884  mdo-miR-7385g-2-3p  MIMAT0050492   AGCAUAGAAUGUCAGGUCUAG

[48885 rows x 3 columns]

In [ ]:
df_mir_seq_convert.to_csv(r"/content/drive/MyDrive/miRNA/df_mir_seq_convert.csv", index=False)

In [ ]:
# print(len(mature_name))
def carve_mature(name):
  name = name.split(" ")
  return name[0][1:]

def carve_hairpin(name):
  name = name.split("-")
  re = ""
  for i in range(len(name)-1):
    re += name[i]
    re += "-"
  return re[:-1]
carve_hairpin("hsa-miR-145-5p")

'hsa-miR-145'

In [ ]:
mature_name_carved=[]
hairpin_name_carved=[]
for i in range(len(mature_name)):
  mature_name_carved.append(carve_mature(mature_name[i]))
  hairpin_name_carved.append(carve_hairpin(carve_mature(mature_name[i])))

In [ ]:
search = "hsa-miR-16-1"

# for i in range(len(mature_name)):
#   if search.lower() == hairpin_name_carved[i].lower():
#     print(mature_name[i])
#     print(mature_name_carved[i])
#     print(hairpin_name_carved[i])
#     print(mature_seq[i])


# for i in range(len(mature_name)):
#   if search.lower() == mature_name_carved[i].lower():
#     print(mature_name[i])
#     print(mature_name_carved[i])
#     print(hairpin_name_carved[i])
#     print(mature_seq[i])

for i in range(len(mature_name)):
  if search == mature_name_carved[i] or search.lower() == hairpin_name_carved[i].lower() or search == mature_name[i]:
    print(mature_name[i])
    print(mature_name_carved[i])
    print(hairpin_name_carved[i].lower())

# print(mature_name_carved[0])
# print(hairpin_name_carved[0])
# print(mature_name[0])
hsa-mir-16-1(hairpin)
hsa-miR-16-1-3p(mature)
hsa-miR-16(mature)

>hsa-miR-16-1-3p MIMAT0004489 Homo sapiens miR-16-1-3p
hsa-miR-16-1-3p
hsa-mir-16-1

In [ ]:
print(mature_name_carved[0])
print(hairpin_name_carved[0])
print(mature_name[0])

cel-let-7-5p
>cel-let-7-5p MIMAT0000001 Caenorhabditis elegans let-7
>cel-let-7-5p MIMAT0000001 Caenorhabditis elegans let-7-5p

In [ ]:
hairpin = open("/content/drive/MyDrive/miRNA/hairpin.fa")

# for i in range(30):
#   line = hairpin.readline()
#   print(line)
while line!="":
  line = hairpin.readline()
  # print(line)
  if "hsa-mir-15a" in line:    
    print(line)

# Hairpin

In [ ]:

# with open("/content/drive/MyDrive/miRNA/mature.fa") as file:
#   for line in file:
#     if "MIMAT0000001" in line: print(line.rstrip())

>cel-let-7-5p MIMAT0000001 Caenorhabditis elegans let-7-5p

In [ ]:
hairpin = open("/content/drive/MyDrive/miRNA/hairpin.fa")

for i in range(10):
  line = hairpin.readline()
  print(line)

>cel-let-7 MI0000001 Caenorhabditis elegans let-7 stem-loop

UACACUGUGGAUCCGGUGAGGUAGUAGGUUGUAUAGUUUGGAAUAUUACCACCGGUGAAC

UAUGCAAUUUUCUACCUUACCGGAGACAGAACUCUUCGA

>cel-lin-4 MI0000002 Caenorhabditis elegans lin-4 stem-loop

AUGCUUCCGGCCUGUUCCCUGAGACCUCAAGUGUGAGUGUACUAUUGAUGCUUCACACCU

GGGCUCUCCGGGUACCAGGACGGUUUGAGCAGAU

>cel-mir-1 MI0000003 Caenorhabditis elegans miR-1 stem-loop

AAAGUGACCGUACCGAGCUGCAUACUUCCUUACAUGCCCAUACUAUAUCAUAAAUGGAUA

UGGAAUGUAAAGAAGUAUGUAGAACGGGGUGGUAGU

>cel-mir-2 MI0000004 Caenorhabditis elegans miR-2 stem-loop

In [ ]:

hairpin_name = []

with open("/content/drive/MyDrive/miRNA/hairpin.fa") as file:
  for line in file:
    # print(line)
    if ">" in line:
      hairpin_name.append(line.rstrip())

In [ ]:
hairpin_name

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/miRNA/circulation.csv',encoding = "ISO-8859-1")
df

,category,mir,disease
0,circulation_biomarker_diagnosis_down,hsa-mir-15a,"Leukemia, Lymphocytic, Chronic, B-Cell"
1,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell"
2,circulation_biomarker_diagnosis_down,hsa-mir-143,Colon Neoplasms
3,circulation_biomarker_diagnosis_down,hsa-mir-145,Colon Neoplasms
4,circulation_biomarker_diagnosis_down,hsa-mir-223,"Leukemia, Lymphocytic, Chronic, B-Cell"
...,...,...,...
4769,circulation_biomarker_prognosis_up,hsa-mir-3135b,Plasmodium Falciparum Malaria
4770,circulation_biomarker_prognosis_up,hsa-mir-3613,Plasmodium Falciparum Malaria
4771,circulation_biomarker_prognosis_up,hsa-mir-6126,Plasmodium Falciparum Malaria
4772,circulation_biomarker_prognosis_up,hsa-mir-6780b,Plasmodium Falciparum Malaria
4773,circulation_biomarker_prognosis_up,hsa-mir-200c,Colorectal Carcinoma

In [ ]:
df.iloc[14]["mir"]

'hsa-mir-126'

In [ ]:
def mirToAcc(mir):
  search = mir
  acc = ""
  err = 0
  for i in range(len(hairpin_name)):
    target = hairpin_name[i]
    target = target.split(" ")
    target_mir = target[0][1:]
    if search.lower() == target_mir.lower():
      # print(hairpin_name[i])
      acc = target[1]
      err += 1
  if err > 1: raise BaseException("Find two index.")
  if acc == "": print(mir)
  return acc

mirToAcc("hsa-mir-16")

hsa-mir-16

''

In [ ]:
def findRelated(name):
  search = name
  for i in range(len(hairpin_name)):
    if search.lower() in hairpin_name[i].lower():
      print(hairpin_name[i])
  return 0
findRelated("hsa-mir-126")

>hsa-mir-126 MI0000471 Homo sapiens miR-126 stem-loop
>hsa-mir-1264 MI0003758 Homo sapiens miR-1264 stem-loop
>hsa-mir-1260a MI0006394 Homo sapiens miR-1260a stem-loop
>hsa-mir-1261 MI0006396 Homo sapiens miR-1261 stem-loop
>hsa-mir-1262 MI0006397 Homo sapiens miR-1262 stem-loop
>hsa-mir-1263 MI0006398 Homo sapiens miR-1263 stem-loop
>hsa-mir-1265 MI0006401 Homo sapiens miR-1265 stem-loop
>hsa-mir-1266 MI0006403 Homo sapiens miR-1266 stem-loop
>hsa-mir-1267 MI0006404 Homo sapiens miR-1267 stem-loop
>hsa-mir-1268a MI0006405 Homo sapiens miR-1268a stem-loop
>hsa-mir-1269a MI0006406 Homo sapiens miR-1269a stem-loop
>hsa-mir-1260b MI0014197 Homo sapiens miR-1260b stem-loop
>hsa-mir-1268b MI0016748 Homo sapiens miR-1268b stem-loop
>hsa-mir-1269b MI0016888 Homo sapiens miR-1269b stem-loop

0

In [ ]:
#>ath-MIR172d MI0000992 Arabidopsis thaliana miR172d stem-loop

# def mirToAcc(mir):
#   search = mir
#   acc = ""
#   err = 0
#   target = ""
#   for i in range(len(hairpin_name)):
#     if search.lower() in hairpin_name[i].lower():
      
#       target = hairpin_name[i]
#       err += 1
#       if err > 1: print(hairpin_name[i])
#   if target != "":
#     target = target.split(" ")
#     return target[1]
#   else:
#     print("ERRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRROR", mir)
#     return ""
  

# mirToAcc("hsa-mir-16")

>hsa-mir-16-2 MI0000115 Homo sapiens miR-16-2 stem-loop

'MI0000115'

In [ ]:
import tqdm
acc = []

from tqdm import tqdm 
for i in tqdm(range(4774)):
  acc.append(mirToAcc(df.iloc[i]["mir"]))
  # print(i)

In [ ]:
count = 0
for i in range(len(acc)):
  if acc[i]=="": count+=1
count

719

In [ ]:
acc[:10]

['MI0000069',
 '',
 'MI0000459',
 'MI0000461',
 'MI0000300',
 'MI0000087',
 'MI0000735',
 'MI0000267',
 'MI0000446',
 'MI0000470']

In [ ]:
df

,category,mir,disease,acc
0,circulation_biomarker_diagnosis_down,hsa-mir-15a,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000069
2,circulation_biomarker_diagnosis_down,hsa-mir-143,Colon Neoplasms,MI0000459
3,circulation_biomarker_diagnosis_down,hsa-mir-145,Colon Neoplasms,MI0000461
4,circulation_biomarker_diagnosis_down,hsa-mir-223,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000300
5,circulation_biomarker_diagnosis_down,hsa-mir-29a,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000087
...,...,...,...,...
4769,circulation_biomarker_prognosis_up,hsa-mir-3135b,Plasmodium Falciparum Malaria,MI0016809
4770,circulation_biomarker_prognosis_up,hsa-mir-3613,Plasmodium Falciparum Malaria,MI0016003
4771,circulation_biomarker_prognosis_up,hsa-mir-6126,Plasmodium Falciparum Malaria,MI0021260
4772,circulation_biomarker_prognosis_up,hsa-mir-6780b,Plasmodium Falciparum Malaria,MI0022681
4773,circulation_biomarker_prognosis_up,hsa-mir-200c,Colorectal Carcinoma,MI0000650

In [ ]:
df_acc = df
df_acc['acc'] = acc
df_acc.drop(df_acc[(df_acc['acc'] == "")].index, inplace=True)
df_acc.reset_index(drop=True, inplace=True)
df_acc

,category,mir,disease,acc
0,circulation_biomarker_diagnosis_down,hsa-mir-15a,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000069
1,circulation_biomarker_diagnosis_down,hsa-mir-143,Colon Neoplasms,MI0000459
2,circulation_biomarker_diagnosis_down,hsa-mir-145,Colon Neoplasms,MI0000461
3,circulation_biomarker_diagnosis_down,hsa-mir-223,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000300
4,circulation_biomarker_diagnosis_down,hsa-mir-29a,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000087
...,...,...,...,...
4050,circulation_biomarker_prognosis_up,hsa-mir-3135b,Plasmodium Falciparum Malaria,MI0016809
4051,circulation_biomarker_prognosis_up,hsa-mir-3613,Plasmodium Falciparum Malaria,MI0016003
4052,circulation_biomarker_prognosis_up,hsa-mir-6126,Plasmodium Falciparum Malaria,MI0021260
4053,circulation_biomarker_prognosis_up,hsa-mir-6780b,Plasmodium Falciparum Malaria,MI0022681
4054,circulation_biomarker_prognosis_up,hsa-mir-200c,Colorectal Carcinoma,MI0000650

In [ ]:
import requests
from bs4 import BeautifulSoup

In [ ]:
def getMatureName(site):
  response = requests.get(site)
  soup = BeautifulSoup(response.text, "html.parser")
  h2s = soup.find_all('h2')
  MatureName = []
  for h in h2s:
    h = str(h)
    if "Mature sequence" in h:
      MatureName.append(h[6:-6].replace("Mature sequence ",""))
  return MatureName
site = r"https://www.mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0000069"
getMatureName(site)

['hsa-miR-15a-5p', 'hsa-miR-15a-3p']

In [ ]:
temp = df_acc.iloc[0]
temp["MatureName"] = 5

d = {  'category': [temp['category']],
     'mir': [temp['mir']],
     'disease': [temp['disease']],
     'acc': [temp['acc']],
     'MatureName': [temp['MatureName']]}
df_MN = pd.DataFrame(data=d)
df_MN
# d = {  'category': [temp['category']],
#      'mir': [temp['mir']],
#      'disease': [temp['disease']],
#      'acc': [temp['acc']],
#      'MatureName': [temp['MatureName']]}
# df_temp = pd.DataFrame(data=d)
# df.append(df2, ignore_index=True)df_MN.append(df_temp, ignore_index=True)
# df_MN

,category,mir,disease,acc,MatureName
0,circulation_biomarker_diagnosis_down,hsa-mir-15a,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000069,5

In [ ]:
d = {  'category': [temp['category']],
     'mir': '8787',
     'disease': [temp['disease']],
     'acc': [temp['acc']],
     'MatureName': [temp['MatureName']]}
df_temp = pd.DataFrame(data=d)
df_temp

,category,mir,disease,acc,MatureName
0,circulation_biomarker_diagnosis_down,8787,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000069,5

In [ ]:
df_acc

In [ ]:
df_MatureName = ""
df_MatureName == ""

True

In [ ]:
is_created = False
for i in tqdm(range(len(df_acc))):
# for i in tqdm(range(10)):
  site = r"https://www.mirbase.org/cgi-bin/mirna_entry.pl?acc=" + df_acc.iloc[i]["acc"]
  MatureNames = getMatureName(site)
  for MatureName in MatureNames:

    temp = df_acc.iloc[i]
    temp["MatureName"] = MatureName

    d = {  'category': [temp['category']],
        'mir': [temp['mir']],
        'disease': [temp['disease']],
        'acc': [temp['acc']],
        'MatureName': [temp['MatureName']]}

    if is_created == False:
      df_MatureName = pd.DataFrame(data=d)
      is_created = True
    else:
      df_temp = pd.DataFrame(data=d)
      df_MatureName = df_MatureName.append(df_temp, ignore_index = True)

  if i % 100 == 0:
    df_MatureName.to_csv(r"/content/drive/MyDrive/miRNA/df_MatureName.csv", index=False)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4055/4055 [56:37<00:00,  1.19it/s]

In [ ]:
df_MatureName

,category,mir,disease,acc,MatureName
0,circulation_biomarker_diagnosis_down,hsa-mir-15a,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000069,hsa-miR-15a-5p
1,circulation_biomarker_diagnosis_down,hsa-mir-15a,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000069,hsa-miR-15a-3p
2,circulation_biomarker_diagnosis_down,hsa-mir-143,Colon Neoplasms,MI0000459,hsa-miR-143-5p
3,circulation_biomarker_diagnosis_down,hsa-mir-143,Colon Neoplasms,MI0000459,hsa-miR-143-3p
4,circulation_biomarker_diagnosis_down,hsa-mir-145,Colon Neoplasms,MI0000461,hsa-miR-145-5p
...,...,...,...,...,...
7745,circulation_biomarker_prognosis_up,hsa-mir-6126,Plasmodium Falciparum Malaria,MI0021260,hsa-miR-6126
7746,circulation_biomarker_prognosis_up,hsa-mir-6780b,Plasmodium Falciparum Malaria,MI0022681,hsa-miR-6780b-5p
7747,circulation_biomarker_prognosis_up,hsa-mir-6780b,Plasmodium Falciparum Malaria,MI0022681,hsa-miR-6780b-3p
7748,circulation_biomarker_prognosis_up,hsa-mir-200c,Colorectal Carcinoma,MI0000650,hsa-miR-200c-5p
7749,circulation_biomarker_prognosis_up,hsa-mir-200c,Colorectal Carcinoma,MI0000650,hsa-miR-200c-3p

In [ ]:
for i in range(len(df_acc)):
  site = df_acc

4055

In [ ]:
def getMIMAT(site):
  count = 0
  accessions = []
  response = requests.get(site)
  soup = BeautifulSoup(response.text, "html.parser")
  for i in range(len(response.json()["data"])):
    if "MIMAT" in response.json()["data"][i]["accession"]: accessions.append(response.json()["data"][i]["accession"])
    count += 1
    if count > 5: return []
  return accessions
getMIMAT(r"https://www.mirbase.org/cgi-bin/textsearch_json.pl?q=hsa-mir-20")

[]

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/miRNA/circulation.csv',encoding = "ISO-8859-1")
df_sMIMAT = df
df_sMIMAT['acc'] = acc
df_sMIMAT.drop(df_sMIMAT[(df_sMIMAT['acc'] != "")].index, inplace=True)
df_sMIMAT.reset_index(drop=True, inplace=True)
df_sMIMAT

,category,mir,disease,acc
0,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",
1,circulation_biomarker_diagnosis_down,hsa-mir-106,Leukemia,
2,circulation_biomarker_diagnosis_down,hsa-mir-20,Leukemia,
3,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",
4,circulation_biomarker_diagnosis_down,hsa-let-7a,Polycythemia Vera,
...,...,...,...,...
714,circulation_biomarker_prognosis_up,hsa-mir-181b,Breast Neoplasms,
715,circulation_biomarker_prognosis_up,hsa-mir-499,Atrial Fibrillation,
716,circulation_biomarker_prognosis_up,hsa-mir-103a,"Diabetes Mellitus, Type 1",
717,circulation_biomarker_prognosis_up,hsa-mir-509,"Leukemia, Myeloid, Acute",
718,circulation_biomarker_prognosis_up,hsa-mir-1273g,Ovarian Neoplasms,

In [ ]:
is_created = False
for i in tqdm(range(len(df_sMIMAT))):
# for i in tqdm(range(10)):
  site = r"https://www.mirbase.org/cgi-bin/textsearch_json.pl?q=" + df_sMIMAT.iloc[i]["mir"]
  MIMATs = getMIMAT(site)
  # print(site)
  if MIMATs != []:
    for MIMAT in MIMATs:

      temp = df_sMIMAT.iloc[i]
      temp["MIMAT"] = MIMAT

      d = {  'category': [temp['category']],
          'mir': [temp['mir']],
          'disease': [temp['disease']],
          'acc': [temp['acc']],
          'MIMAT': [temp['MIMAT']]}

      if is_created == False:
        df_MIMAT = pd.DataFrame(data=d)
        is_created = True
      else:
        df_temp = pd.DataFrame(data=d)
        df_MIMAT = df_MIMAT.append(df_temp, ignore_index = True)

  if i % 100 == 0:
    df_MIMAT.to_csv(r"/content/drive/MyDrive/miRNA/df_MIMAT.csv", index=False)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 719/719 [10:04<00:00,  1.19it/s]

In [ ]:
df_MIMAT

,category,mir,disease,acc,MIMAT
0,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0004489
1,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0004518
2,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0000069
3,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0004489
4,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0004518
...,...,...,...,...,...
956,circulation_biomarker_prognosis_up,hsa-mir-181b,Breast Neoplasms,,MIMAT0031893
957,circulation_biomarker_prognosis_up,hsa-mir-181b,Breast Neoplasms,,MIMAT0022692
958,circulation_biomarker_prognosis_up,hsa-mir-103a,"Diabetes Mellitus, Type 1",,MIMAT0000101
959,circulation_biomarker_prognosis_up,hsa-mir-103a,"Diabetes Mellitus, Type 1",,MIMAT0037306
960,circulation_biomarker_prognosis_up,hsa-mir-103a,"Diabetes Mellitus, Type 1",,MIMAT0009196

In [ ]:
import numpy as np

In [ ]:
print(np.any(n))

True

In [ ]:
seq = []
MatureName=[]
for i in range(len(df_MIMAT)):
  n = df_mir_seq_convert[(df_mir_seq_convert["MIMAT"] == df_MIMAT.iloc[i]['MIMAT'])]
  # print(n)
  if np.any(n):
    # print(n.values[0])
    seq.append(n['mature_seq'].values[0])
    MatureName.append(n['MatureName'].values[0])
  else:
    seq.append("")
    MatureName.append("")

# df_sMIMAT[(df_sMIMAT['acc'] == "")].index
# df_sMIMAT[(df_sMIMAT['acc'] != "")]

In [ ]:
len(seq)

961

In [ ]:
df_MIMAT['seq'] = seq
df_MIMAT['MatureName'] = MatureName
df_MIMAT

,category,mir,disease,acc,MIMAT,seq,MatureName
0,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0004489,CCAGUAUUAACUGUGCUGCUGA,hsa-miR-16-1-3p
1,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0004518,CCAAUAUUACUGUGCUGCUUUA,hsa-miR-16-2-3p
2,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0000069,UAGCAGCACGUAAAUAUUGGCG,hsa-miR-16-5p
3,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0004489,CCAGUAUUAACUGUGCUGCUGA,hsa-miR-16-1-3p
4,circulation_biomarker_diagnosis_down,hsa-mir-16,"Leukemia, Lymphocytic, Chronic, B-Cell",,MIMAT0004518,CCAAUAUUACUGUGCUGCUUUA,hsa-miR-16-2-3p
...,...,...,...,...,...,...,...
956,circulation_biomarker_prognosis_up,hsa-mir-181b,Breast Neoplasms,,MIMAT0031893,CUCACUGAUCAAUGAAUGCA,hsa-miR-181b-2-3p
957,circulation_biomarker_prognosis_up,hsa-mir-181b,Breast Neoplasms,,MIMAT0022692,CUCACUGAACAAUGAAUGCAA,hsa-miR-181b-3p
958,circulation_biomarker_prognosis_up,hsa-mir-103a,"Diabetes Mellitus, Type 1",,MIMAT0000101,AGCAGCAUUGUACAGGGCUAUGA,hsa-miR-103a-3p
959,circulation_biomarker_prognosis_up,hsa-mir-103a,"Diabetes Mellitus, Type 1",,MIMAT0037306,GGCUUCUUUACAGUGCUGCCUUG,hsa-miR-103a-1-5p
960,circulation_biomarker_prognosis_up,hsa-mir-103a,"Diabetes Mellitus, Type 1",,MIMAT0009196,AGCUUCUUUACAGUGCUGCCUUG,hsa-miR-103a-2-5p

In [ ]:
df_MIMAT.to_csv(r"/content/drive/MyDrive/miRNA/df_MIMAT.csv", index=False)

In [ ]:
seq = []
MIMAT = []
for i in range(len(df_MatureName)):
  n = df_mir_seq_convert[(df_mir_seq_convert["MatureName"] == df_MatureName.iloc[i]['MatureName'])]
  # print(n)
  if np.any(n):
    # print(n.values[0])
    seq.append(n['mature_seq'].values[0])
    MIMAT.append(n['MIMAT'].values[0])
  else:
    seq.append("")
    MIMAT.append("")

In [ ]:
len(seq)

7750

In [ ]:
len(MIMAT)

7750

In [ ]:
df_MatureName['seq'] = seq
df_MatureName['MIMAT'] = MIMAT
df_MatureName

,category,mir,disease,acc,MatureName,seq,MIMAT
0,circulation_biomarker_diagnosis_down,hsa-mir-15a,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000069,hsa-miR-15a-5p,UAGCAGCACAUAAUGGUUUGUG,MIMAT0000068
1,circulation_biomarker_diagnosis_down,hsa-mir-15a,"Leukemia, Lymphocytic, Chronic, B-Cell",MI0000069,hsa-miR-15a-3p,CAGGCCAUAUUGUGCUGCCUCA,MIMAT0004488
2,circulation_biomarker_diagnosis_down,hsa-mir-143,Colon Neoplasms,MI0000459,hsa-miR-143-5p,GGUGCAGUGCUGCAUCUCUGGU,MIMAT0004599
3,circulation_biomarker_diagnosis_down,hsa-mir-143,Colon Neoplasms,MI0000459,hsa-miR-143-3p,UGAGAUGAAGCACUGUAGCUC,MIMAT0000435
4,circulation_biomarker_diagnosis_down,hsa-mir-145,Colon Neoplasms,MI0000461,hsa-miR-145-5p,GUCCAGUUUUCCCAGGAAUCCCU,MIMAT0000437
...,...,...,...,...,...,...,...
7745,circulation_biomarker_prognosis_up,hsa-mir-6126,Plasmodium Falciparum Malaria,MI0021260,hsa-miR-6126,GUGAAGGCCCGGCGGAGA,MIMAT0024599
7746,circulation_biomarker_prognosis_up,hsa-mir-6780b,Plasmodium Falciparum Malaria,MI0022681,hsa-miR-6780b-5p,UGGGGAAGGCUUGGCAGGGAAGA,MIMAT0027572
7747,circulation_biomarker_prognosis_up,hsa-mir-6780b,Plasmodium Falciparum Malaria,MI0022681,hsa-miR-6780b-3p,UCCCUUGUCUCCUUUCCCUAG,MIMAT0027573
7748,circulation_biomarker_prognosis_up,hsa-mir-200c,Colorectal Carcinoma,MI0000650,hsa-miR-200c-5p,CGUCUUACCCAGCAGUGUUUGG,MIMAT0004657
7749,circulation_biomarker_prognosis_up,hsa-mir-200c,Colorectal Carcinoma,MI0000650,hsa-miR-200c-3p,UAAUACUGCCGGGUAAUGAUGGA,MIMAT0000617

In [ ]:
df_MatureName.to_csv(r"/content/drive/MyDrive/miRNA/df_MatureName.csv", index=False)